### DISCUSSION TITLE
Voting on `publications` and `supporting documents` association slots

### DISCUSSION THREAD

**Discussion by mbrush** [biolink/biolink-model#1234] [General]
This discussion was created for voting on one of the specific issues arising in #1107 - whether to maintain separate `publications` and `supporting documents` association slots, or collapse these into one. 
 
----------------------

### Background:
The Biolink model currently has two association slots for linking a Statement or other information entity to a document/publication that 'supports it' (i.e. report the information or report evidence or provenance supporting it):

````
 supporting documents:
    is_a: association slot
    description: >-
      One or more referencable documents that report the statement expressed in an Association, or provide 
      information used as evidence supporting this statement.
    range: uriorcurie
    multivalued: true
    examples:
      - value: PMID:12345678
 
  publications:
    aliases: ["supporting publications"]
    singular_name: publication
    description: >-
      One or more publications that report the statement expressed in an Association, or provide information used as 
      evidence supporting this statement.
    is_a: supporting documents
    multivalued: true
    range: publication
````

 
The `publications` property predates the `supporting_documents` property, and is widely used across KPs to link Edges to pubs that support them. 
 
The `supporting_documents` property was recently added to support the TMKP in linking `Text Mining Study Result` objects to documents from which the mined text/sentence was pulled (These study result objects help to organize EPC information about a particular analysis of a sentence, so that users can keep EPC for different sentences that support a single text-mined Edge separate in the TRAPI message structure). 
 
TMKP wanted a property more general than 'publications' because not all documents their tools mine are publications in the traditional sense (e.g. some are things like patents, or product inserts, etc).
 
The issue largely comes down to the semantics of what a 'Publication' is.  Biolink defines it as follows: 
> "any published piece of information. Can refer to a whole publication, its encompassing publication (i.e. journal or book) or to a part of a  publication, if of significant knowledge scope (e.g. a figure, figure legend, or section highlighted by NLP). The scope is intended to be general and include information published on the web, as well as printed materials, either directly or in one of the Publication Biolink category subclasses."
 
The definition here seems broad enough that it might cover the types of edge cases TMKP brought to the table above (patents, product inserts).  
 
On the 2-28-23 EPC Call we discussed the possibility of collapsing these into a single property to simplify the model and data.  Three options were presented to choose from.  This ticket provides a forum for discussion and casting votes.
 
--------

### Voting:
We will use the voting scheme described below:
 
+2 Highest (heart) - Love this option
+1 High (thumb up) - Like this option
0 Medium (eyes) - Meh, no strong feelings either way about this option)
-1 Low Priority (thumb down) - We should not do this option
 
Please cast a vote **using one of these symbols for EACH of the options below** by the next EPC call on March 14, 2023 **(i.e. don't just vote for one - pick the symbol that best expresses your feelings about all three options)**.  
And feel free to use this Discussion to argue your case for your preferred choice, pose questions, or proposed additional options for consideration.
