### ISSUE TITLE
Biological Inheritance model in Biolink

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#1064]
**Context of the feature request related to a problem:**

We would like to better model MONDO biological inheritance (see https://github.com/monarch-initiative/monarch-ingest/issues/295)

**Working group (or team) this request originate from:**

Maybe need a fresh review of the Biolink Model representing this type of data originated Monarch Initiative.

**The solution we might like**

See full use case discussion below.

**Relevant members for discussion:**

@sierra-moxon, @mbrush, @cmungall, @kevinschaper

**Other Relevant XRefs:**

* [@mbrush - Monarch Initiative GENO Ontology issue](https://github.com/monarch-initiative/GENO-ontology/issues/22) 
* [@mbrush - Monarch Initiative Dipper issue](https://github.com/monarch-initiative/dipper/issues/383)

# Full Use Case
The Biolink Model does already defines [**inheritance** _is_a_ **organism_attribute** _is_a_ **attribute**](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L8084).  Such attributes may be connected to nodes (**biolink:NamedThing** and its descendant categories) and edges (**biolink:Association**) through the [_has_attribute_ ](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L287)slot inherited from the **biolink:Entity** parent class. Specifically:

```yaml
inheritance:
    is_a: organism attribute
    description: >-
      The pattern or 'mode' in which a particular genetic trait or disorder is passed from one
      generation to the next, e.g. autosomal dominant, autosomal recessive, etc.
    exact_mappings:
      - HP:0000005
      - GENO:0000141
      - NCIT:C458271
```
and
```
  organism attribute:
    is_a: attribute
    description: >-
      describes a characteristic of an organismal entity.
    exact_mappings:
      # Organism Attribute
      - STY:T032
```
By its definition, the latter implies a _domain_ of **biolink:OrganismalEntity**:

```
  organismal entity:
    description: >-
      A named entity that is either a part of an organism, a whole organism,
      population or clade of organisms, excluding chemical entities
etc....
```
which is not exactly what one might expect for the property of genetic inheritance. Rather, as a minimum, one might wish to rather see a definition associating the _biolink:inheritance_ attribute with the **biolink:DiseaseOrPhenotypicFeature** category.

This confusion may have arisen given the close match concept of [biolink:phenotypic_quality](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L8073): 

```
  phenotypic quality:
    aliases: ['phenotypic properties']
    is_a: organism attribute
    description: >-
      A property of a phenotype
    examples:
      - value: weight
```

seems more naturally directly associated with an organism.

Should the semantics of _biolink:inheritance_ somehow be repaired. If so, how? Here are some ideas:

### Option A - Move the _biolink:inheritance_ attribute directly under **biolink:DiseaseOrPhenotypicFeature**

```yaml
inheritance:
    is_a: disease or phenotypic feature attribute
    etc...
```
and
```
  disease or phenotypic feature attribute:
    is_a: attribute
    description: >-
      describes a characteristic of a disease or phenotypic feature.
    etc...
```
then apply it as follows:
```
disease or phenotypic feature:
    ...
    is_a: biological entity
    slot_usage:
      has attribute:
        description: >-
          may often be an disease or phenotypic feature attribute
    etc....
```

### Option B - Model the `biolink:inheritance` relationship analogous to the `biolink:has_taxon` slot. 

The `has_taxon` slot is defined as a _biolink:predicate_, as follows:
```
  in taxon:
    aliases: ['instance of', 'is organism source of gene product', 'organism has gene', 'gene found in organism',' gene product has organism source']
    is_a: related to at instance level
    domain: thing with taxon
    range: organism taxon
    annotations:
      canonical_predicate: true
    description: >-
      connects an entity to its taxonomic classification. Only certain kinds
      of entities can be taxonomically classified; see 'thing with taxon'
    in_subset:
      - translator_minimal
    exact_mappings:
      - RO:0002162
      - WIKIDATA_PROPERTY:P703
    narrow_mappings:
      - RO:0002160
```
plus its inverse:
```
  taxon of:
    is_a: related to at instance level
    inverse: in taxon
    domain: organism taxon
    range: thing with taxon
```
with an associated `mixin` defined:

```
  thing with taxon:
    mixin: true
    description: >-
      A mixin that can be used on any entity that can be taxonomically classified.
      This includes individual organisms; genes, their products and other molecular
      entities; body parts; biological processes
    slots:
      - in taxon
```
then used every where needed: biolink:BiologicalEntity (category), biolink:NucleicAcidEntity (category), (redundantly in) biolink:DiseaseOrPhenotypicFeature (category) and biolink:GenomicBackgroundExposure (_is_a biolink:attribute_)

BTW, there is an interesting question about why these two slots are modelled as `biolink:predicate` instances and not as _biolink:attribute_ definitions(?). Conversely, since they are modelled as predicates, it seems inconsistent to inject `biolink:taxon_of` as a slot in  `thing with taxon` then apply the `mixin` to node category classes (i.e.  **biolink:BiologicalEntity** and **biolink:NucleicAcidEntity**), plus in another biolink:attribute definition (_biolink:genomic_background_exposure_)?

The above concern notwithstanding, we might consider treating the concept of genetic Inheritance in a similar fashion, by first converting Inheritance into a _biolink:category_ instead of an _biolink:attribute_:
```
inheritance:
    is_a: named thing
    description: >-
      The pattern or 'mode' in which a particular genetic trait or disorder is passed from one
      generation to the next, e.g. autosomal dominant, autosomal recessive, etc.
    exact_mappings:
      - HP:0000005
      - GENO:0000141
      - NCIT:C458271
```
then used in suitable slots:
```
has inheritance:
    is_a: related to at instance level
    domain: thing with inheritance
    range: inheritance
    annotations:
      canonical_predicate: true
etc...
```
and
```
inheritance of:
    is_a: related to at instance level
    inverse: has inheritance
    domain: inheritance
    range: thing with inheritance
```
with the associated `mixin` defined:

```
  thing with inheritance:
    mixin: true
    description: >-
...
    slots:
      - has inheritance
```
then used accordingly:
````
  disease or phenotypic feature:
   etc...
    is_a: biological entity
    mixins:
    - thing with inheritance
````
### Option C - Model things the Biolink Model 3.0 way?

Perhaps Genetic Inheritance can be modelled as a novel kind of node qualifier? @sierra-moxon and/or @mbrush may wish to elaborate this option here?

### Option D - Annotated Mode of Inheritance as a biolink:Association

This option models `biolink:has_inheritance` and `biolink:inheritance_of` as Biolink _predicates_ (as Option B explains is inadvertently done with slots like `biolink:in_taxon`) and `biolink:Inheritance` as a node `biolink:category` (i.e. _is_a_: **biolink:NamedThing**) then annotates instances of **biolink:DiseaseOrPhenotypicFeature** with their mode of inheritance as _Subject-Predicate-Object_ statements (a **biolink:Association**). For example:

([Asperger syndrome, X-linked, susceptibility to, 1 (MONDO:0010340)](https://api-gcp.monarchinitiative.org/api/bioentity/disease/MONDO:0010340?fetch_objects=false&unselect_evidence=true&exclude_automatic_assertions=true&use_compact_associations=false&get_association_counts=true&rows=1): **biolink:DiseaseOrPhenotypicFeature**)  - [`biolink:has_inheritance`] -> ([X-linked inheritance (HP:0001417)](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0001417): **biolink:Inheritance**) 

## Additional Thoughts
 
The values of Inheritance could perhaps be mapped as enums onto available mode of inheritance ontology: perhaps [HP Mode of Inheritance terms](https://hpo.jax.org/app/browse/term/HP:0000005) or [NCIT](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C45827&lang=en&viewMode=All&siblings=false)?
