### ISSUE TITLE
Can the biolink:subject_of_investigation mixin tag other worthy targets of studies?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#1101]
The current model has: 

```yaml
  subject of investigation:
    mixin: true
    description: >-
      An entity that has the role of being studied in an investigation, study, or experiment

  material sample:
    aliases: [ 'biospecimen', 'sample', 'biosample', 'physical sample' ]
    is_a: physical entity
    mixins:
      - subject of investigation
etc...
  ```

I don't know how we currently represent various subjects of clinical studies, but perhaps at least patients or probands could be added to the list. Not sure what other categories might benefit from this mixin.
