### ISSUE TITLE
For mixins, must the value listed in the is_a slot also be a mixin?

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#1111]
**Question from Amy Glen (Expander Agent)**
Biolink help desk kind of question: I was under the impression that for mixins, the value listed in their is_a slot must also be a mixin. Is that still true with Biolink 3.0?
I noticed that in Biolink 3.0.3, [exposure event](https://github.com/biolink/biolink-model/blob/52e85fce4917dbaf313b68c3c4a2558c627069d0/biolink-model.yaml#L9474-L9486) has mixin: true, but is_a: named thing. (Where named thing is of course not a mixin.) This breaks some of our ARAX code so I wanted to make sure this wasn't a mistake?
[biolink-model.yaml](https://github.com/biolink/biolink-model/blob/52e85fce4917dbaf313b68c3c4a2558c627069d0/biolink-model.yaml)
```
  exposure event:
    is_a: named thing
    aliases: [ 'exposure', 'experimental condition' ]
    mixin: true
    slots:
      - timepoint
    description: >-
      A (possibly time bounded) incidence of a feature of the environment of an organism that
      influences one or more phenotypic features of that organism, potentially mediated by genes
    exact_mappings:
      - XCO:0000000
    in_subset:
      - model_organism_database
```
