### ISSUE TITLE
domain/range mismatch for sequence variant predicates

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1186]
* `gene` is domain of predicates `has frameshift variant`, `has missense variant`, `has nearby variant`, `has non coding variant`, `has nonsense variant`, `has splice site variant` and `has synonymous variant` that are all subpredicates of `has sequence variant` that has domain `nucleic acid entity`. 

* respectively, `gene` is range of predicates `is frameshift variant of`, `is missense variant of`, `is nearby variant of`, `is non coding variant of`, `is nonsense variant of`, `is splice site variant of` and `is synonymous variant of` that are all subpredicates of `is sequence variant of` that has range `nucleic acid entity`.

I expect the subpredicates to have a domain (resp. range) that is included in the domains (resp. ranges) of all its ancestors, but `gene` is **not** a subclass of `nucleic acid entity`:

```
  gene:
    is_a: biological entity
    mixins:
      - gene or gene product
      - genomic entity
      - chemical entity or gene or gene product
      - physical essence
      - ontology class

  biological entity:
    is_a: named thing
    aliases: [ 'bioentity' ]
    abstract: true
    mixins:
      - thing with taxon
```

```
  nucleic acid entity:
    is_a: molecular entity
    aliases: [ 'sequence feature', 'genomic entity' ]
    mixins:
      - genomic entity
      - thing with taxon
      - physical essence
      - ontology class      

  molecular entity:
    is_a: chemical entity
    
  chemical entity:
    is_a: named thing
    mixins:
      - physical essence
      - chemical or drug or treatment # issue 701
      - chemical entity or gene or gene product
      - chemical entity or protein or polypeptide     
```

It seems that `genomic entity` would be a better fit for these domains and ranges.
