### ISSUE TITLE
Loop in permissible values hierarchy of ChemicalOrGeneOrGeneProductFormOrVariantEnum

### ISSUE THREAD

**Issue by vincentvialard** [biolink/biolink-model#1215]
Even if it is at the moment unclear whether permissible values hierarchies should be accepted (see [LinkML issue #1261](https://github.com/linkml/linkml/issues/1261)), it sure should not contain loops like this one:

```
  ChemicalOrGeneOrGeneProductFormOrVariantEnum:
    permissible_values:
      genetic_variant_form:
        is_a: modified_form
      modified_form:
        is_a: genetic_variant_form
      ...
```

I did not spot any other.
