### ISSUE TITLE
remove "singular_name" metadata from slots as it causes confusion with TRAPI

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#1268]
a TRAPI message should fail validation if it uses: "biolink:publication" instead of "biolink:publications".   In Biolink, the publications slot/attribute has a 'singular_name' field that confuses this validation:
```
  publications:
    aliases: ["supporting publications"]
    singular_name: publication
    description: >-
      One or more publications that report the statement expressed in an Association, or provide information used as 
      evidence supporting this statement.
    is_a: supporting documents
    multivalued: true
    range: publication
```
We use this metadata tag very sparingly in Biolink at the moment, only on "authors", "publications", and "qualifiers".  As "qualifiers" (as a multivalued slot) is being deprecated, and this issue was raised for "publications", it makes sense to remove this for "authors" as well.
