### ISSUE TITLE
How to import/use/extend biolink model in our schema

### ISSUE THREAD

**Issue by sooyounga** [biolink/biolink-model#1278]
**Question:**
We are trying to use the existing biolink model's slots/attributes in our own schema, and the way we understood was to import biolink model in `prefixes` and `imports`, and reference it in `is_a: biolink:gene` for example. We've tried some variations of this understanding and are not quite able to get it right to get past the error of it being unable to recognize the is_a. 
We've also tried using slot definition, by putting it under `slot_uri`.

How do we go about importing biolink model exactly? 

For example:
```
prefixes:
  linkml: https://w3id.org/linkml/
  biolink: https://w3id.org/biolink
imports:
  - linkml:types
  - biolink

classes:
  gene annotation:
  is_a: biolink:gene
...
  slots:
    - provided by
```
we wouldn't be able to go import it properly for it to recognize `provided by` from biolink gene model, even if we move it to slot_uri.

**Comment by sierra-moxon** [comment]
Hi @sooyounga -

thanks for reaching out!  there were a couple of issues here, the first was fixed in this repo (the URL expansion for the `biolink` prefix in this repo was set to `https://w3id.org/biolink/vocab` and it should have been `https://w3id.org/biolink/`.  I've fixed that. The issue was that LinkML knows how to expand a prefix to retrieve the YAML file for a model by appending the `local` part of the id to the prefix URI ([and adding a `.yaml` by default](https://linkml.io/linkml/schemas/imports.html)).  Because Biolink's YAML schema is called `biolink-model.yaml` in the repo,  we need to specify `biolink:biolink-model` in the imports for the LinkML import code to work.
 
With that fix, and the change to your model below, I am able to reference the Biolink `gene` class via import:

```
prefixes:
  linkml: https://w3id.org/linkml/
  biolink: https://w3id.org/biolink/
imports:
  - linkml:types
  - biolink:biolink-model

classes:
  gene annotation:
  is_a: gene

  slots:
    - provided by
 ```
(notice the extra slash at the end of the prefix declaration, the `gene` syntax in the `gene annotation` class, and the `biolink:biolink-model` import syntax). 

If I've answered your question, please feel free to close this issue; alternatively, I'll be back around to it in a few days to close.
