### ISSUE TITLE
domain and range on "diagnoses" seem odd

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#1295]
```
  diagnoses:
    is_a: related to at instance level
    description: >-
      a relationship that identifies the nature of (an illness or other problem) by examination of the symptoms.
    domain: chemical or drug or treatment
    range: disease or phenotypic feature
    annotations:
      canonical_predicate: true
    close_mappings:
      - NCIT:C15220  # diagnosis
      - SIO:001331  # diagnosis
    exact_mappings:
      - DrugCentral:5271
      - SEMMEDDB:DIAGNOSES
 ```

in working on #1292, I noticed the domain in particular on `diagnoses` seems a little odd.  Do we mean `chemical or drug or treatment` in the sense of a diagnostic aid or indicator of disease?
