### ISSUE TITLE
Duplicate `id_prefixes` for all ChemicalEntities, including all possible chemical namespaces on each class

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#1386]
Per our discussion with the Chemical WG in Translator, we would like to replicate the possible chemical namespaces in the `id_prefixes` LinkML meta-model component for all `biolink:ChemicalEntity` descendants in an effort to help validate that data sources that have many kinds of chemical entities (without metadata to tell us what specific kind of chemical entity each identifier represents), can use the higher level biolink categories (like 'biolink:ChemicalEntity') without validation warnings/errors.

More information:
[Slack thread initiated by Colleen Xu](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1689968072363309) on 7/21/2023 about CHEMBL.COMPOUND as primary ID for ChemicalEntity
[ChemicalEnity mappings in the Biolink Model YAML](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L6866)
ChEMBL’s use of Small Molecule as the classification 
in LinkML, we define metamodel components that should be inherited using the inherited component.  Note: id_prefixes are not inherited. 
pre-chemical refactor, these were id_prefixes on biolink:ChemicalSubstance but we moved them purposefully during the chemical refactor.
schema pre-chemical refactor:
https://github.com/biolink/biolink-model/blob/bf2de193f9eeb552eb2e51dc90acc9df9f7d6091/biolink-model.yaml#L5882C1-L5904C33 
current schema for biolink:ChemicalEntity:
https://github.com/biolink/biolink-model/blob/cfd18406cb7b6d2d2e04935b159c03cf5fefdaeb/biolink-model.yaml#L6876
current schema for biolink:SmallMolecule:
https://github.com/biolink/biolink-model/blob/cfd18406cb7b6d2d2e04935b159c03cf5fefdaeb/biolink-model.yaml#L6910

**Comment by RichardBruskiewich** [comment]
Although we say that **`id_prefix`** lists are not inherited, we have at least one helpful mixin that contains a useful id_prefix lis:

```yaml
  gene or gene product:
    description: >-
      A union of gene loci or gene products.
      Frequently an identifier for one will be used as proxy for another
    is_a: macromolecular machine mixin
    mixin: true
    id_prefixes:
      - CHEMBL.TARGET
      - IUPHAR.FAMILY
```

Does BMT therefore validate members of the **`id_prefix`** list of the **`mixin`** in all concrete categories to which it is attached? Moreover, do we have to tag all child categories with the same mixin to get those id_prefixes visible in the child classes (since there is no inheritance of said id_prefix entries)?
