### ISSUE TITLE
alt_description is being used as a complex type

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#156]
`sequence variant` in the latest biolink-model uses `alt_descriptions` as a list of description/source tuples:

```
    alt_descriptions:
      - description: "An enitity that describes a single affected, endogenous allele.  These can be of any type that matches that definition"
        source: AGR
      - description: "A contiguous change at a Location"
        source: VMC
```

Assuming this is correct, meta.yaml needs to be updated to reflect this change.  

We need to address the purpose of the source field -- should we be mapping the prefix (AGR, VMC, ...) to a URI or just carry it as a string?

Also, will the *non* alt-description ever carry a source field and, if so, how?
