### ISSUE TITLE
`category` type doesn't line up with its mapping

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#164]
Category is defined as:
```
  category:
    is_a: node property
    domain: named thing
    range: label type
    description: >-
      Name of the high level ontology class in which this entity is categorized. Corresponds to the label for the biolink entity type class.
      In a neo4j database this MAY correspond to the neo4j label tag
    is_class_field: true
    multivalued: true
    in_subset:
      - translator_minimal
    mappings:
      - "rdf:type"
```
`label type` is defined as a string.  Strings can't be the object of the `rdf:type` predicate
