### ISSUE TITLE
is_a vs. subClass issues

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#182]
The [Biolink model](biolink-model.yaml) asserts:

```
drug is_a chemical substance
chemical substance is_a molecular entity
molecular entity is_a biological entity
```
This represented as:
```
biolink:Drug a biolink:ChemicalSubstance . 
biolink:ChemicalSubstance a biolink:MolecularEntity .
biolink:MolecularEntity a biolink:BiologicalEntity .
```
in [Biolink RDF](rdf/biolink-model.ttl).

`rdf:type` is *not* transitive, meaning that an association whose subject is a Drug is not a valid instance of ChemicalSubstanceToThing association.

Have we conflated 'type' (is_a) with 'subClassOf'

**Comment by hsolbrig** [comment]
Probably my doing. `is_a` is used both in class-class and slot-slot (and, at the moment, class-slot is also allowed) associations.  I'm inclined to not try to get too clever and, instead, define `is_a` for `rdfs:subClassOf` and `is_a_p` (?) for `rdfs:subPropertyOf`.  What do you think?

**Comment by hsolbrig** [comment]
Actually, it still leaves us with a problem.  We have *three* uses of `is_a`:

1.  `class-class`: `"BioSample": { "is_a": "BiologicalEntity"}`
2. `slot-slot`: `"interacts with": { "is_a":  "related_to"}`
2. `instance-class`: `"_:X" {"is_a": "ChemicalToGeneAssociation"}

The first entry maps to `rdfs:subClassOf`, the second to `rdfs:subPropertyOf` and the third to `rdf:type` (???)

I would propose `is_a` for class-class, `subPropertyOf` for slot-slot and `a` for instance-class (assuming that we ARE talking instance-class in the third case.

**Comment by cmungall** [comment]
On 17 Dec 2018, at 9:11, Harold Solbrig wrote:

> Actually, it still leaves us with a problem.  We have *three* uses of 
> `is_a`:
>
> 1.  `class-class`: `"BioSample": { "is_a": "BiologicalEntity"}`
> 2. `slot-slot`: `"interacts with": { "is_a":  "related_to"}`
> 2. `instance-class`: `"_:X" {"is_a": "ChemicalToGeneAssociation"}
>
> The first entry maps to `rdfs:subClassOf`, the second to 
> `rdfs:subPropertyOf`

yep. We can use a more explicit slot in the metamodel if it helps

> and the third to `rdf:type` (???)

hmm, do we have any instances in the model?

**Comment by cmungall** [comment]
foo would be an instance of ChemicalToGeneAssociation, but otherwise the same.

Note that from an OBO modeling POV we may model specific drugs as classes, but we induce the IRIs to be punned here

**Comment by cmungall** [comment]
So if we add a new relation into biolink-model called `type` (Though `a` is cute I think type is more explicit), that is equivalent to rdf:rtype, does that solve things?

**Comment by hsolbrig** [comment]
Actually, I realized that we had a wee bit of problem crossing the "meta-beams".  The way to declare instances is through the slot domain and range attributes.  Starting with the meta-model, which is self defining, we get:

```yaml
metamodel:
    # Model type *instances*
    types:
        uri:
    # Model slot *instances*
    slots:      
       typeof:
          domain: type definition
          range: type definition
       uri:
           domain: type definition
           range: uri
       domain:
          domain: slot definition
          range: class definition
       range:
          domain: slot definition
          range: definition                # type definition or class definition

       # Model *definition* of types  
       types:
          domain: schema definition
          range: type definition
          inlined: true
          multivalued: true

       # Model *definition* of slots
       slots:
         domain: schema definition
         range: slot definition
         inlined: true
         alias: slots

      # Model *definition* of classes
      classes:
         domain: schema definition
         range: class definition
         multivalued: true
         inlined: true

  # Model class *instances*
  classes:
     slot definition:
     class definition:
     schema definition:
```
In the meta world this is a bit confusing, as we are simultaneously defining "slots", "classes", and using said definitions in the definition of the schema `meta`.  The key, however, is once we've explicitly stated that the above model is an instance of `schema definition`, we know the type of everything else.

Now on to the model world.  For the sake of argument, we simplify:
```yaml
model:

   slots:
       root:
           domain: type constraint
           range: uri
       union of:
            domain: type constraint
            range: type constraint
            multivalued: true
       subject:
           domain: association
           range: type constraint
           required: true
       relation:
           domain: association
           range: type constraint
           required: true
       object:
           domain: association
           range: type constraint
           required: true
       reified stuff:
           domain: association
           range: string
           multivalued: true
           description: all the other stuff we tack onto a reified association
      is_a:
          domain: association
          range: association
          description: an association/association refinement

       constraints:
           domain: model instance
           range: type constraint
           multivalued: true
           inlined: true

       associations:
          domain: model instance
          range: association
          multivalued: true
          inlined: true

   classes:
        constraints:
        association:
        model instance:
```
As with the metamodel above, once we assert that any knowledge graph is an instance of `model instance`, all the rest of the information just falls out.  We crossed the meta-boundaries when we assert the following:
```yaml
   genotype to genotype part association:
      is_a: association
      ...
```
My take is that this is not correct.  Instead, we need to assert:
```yaml
core kg:
    type constraints:
        gene:
           root: SO:0000704
        gene product:
           root: WD:Q424689
        gene or gene product:
           union of:
              - gene
              - gene product
        homologous to:
             root: RO:HOM0000001

   associations:
       # This is where you establish the basic model assumptions.  Some examples
       semiformal association:
           subject: RDF.Resource
           predicate: RDF.property
           object: RDF.Resource

       formal association:
            subject: OWL.Class
            predicate: OWL.ObjectProperty
            object: OWL.Class
           
       gene to gene association:
           is_a: formal association.                # Note that this is NOT the metamodel class/class is_a!
           subject: gene or gene product
           object: gene or gene product
       gene to gene homology association:
           is_a: gene to gene association     
           relation: homologous to
```
**NOTE:** the above is simply an approximation of what we are trying to do.  If done correctly, I believe that it will do minimal damage to the model as we have it today.  

The key to the above approach is that `association` and `type constraint` are models and `gene to gene product` is an instance.

(I am about to submit a new biolink-metamodel project to the repository to clearly separate the metamodel from the biolink-model level and to clean/crisp some things up.)
