### ISSUE TITLE
ShEx has wrong predicates for constrained slots

### ISSUE THREAD

**Issue by hsolbrig** [biolink/biolink-model#188]
The ShEx generator is not using the aliases for constrained associations.  As an example the predicate representing `subject` below:
```
  anatomical entity to anatomical entity association:
#      schema: gocam
    is_a: association
    defining_slots:
      - subject
      - object
    slot_usage:
      subject:
        range: anatomical entity
      object:
        range: anatomical entity
```
is emitted in the ShEx definition as `biolink:anatomical_entity_to_anatomical_entity_association_subject` instead of `rdf:subject`
