### ISSUE TITLE
Plural or singular property name 

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#201]

**Comment by lhannest** [comment]
Should multi-valued properties be plural? "Synonyms" and "categories" rather than "synonym" and "category"?

**Comment by TomConlin** [comment]
Are we guaranteeing there is always more than one?
In practice, when referring to an element, I favour the singular.

**Comment by hsolbrig** [comment]
A reason for going plural is, unless the loader can help out, it helps with syntax:

`thing: dog`    
vs
`things:
    - dog
`

Also it allow us to aggregate types:

```
classes:
    thing:
       slots:
           - name
           - flavor
           - spin

slots:
    things:
          domain: somecontainer
           range: thing
           ismultiple: true
```
