### ISSUE TITLE
Drug Exposure and Chemical Substance

### ISSUE THREAD

**Issue by stevencox** [biolink/biolink-model#208]
What do we think of a new biolink-model type - `chemical substance exposure` which describes exposure to a `chemical substance` independent of whether it is intended for the treatment of disease?

We've got clinical data that describes exposures to drugs. But it also describes exposures to things like particulate matter and ozone that are not `intended to treat disease` which is roughly the description of `drug`:
```
  drug:
    is_a: chemical substance
    description: >-
      A substance intended for use in the diagnosis, cure, mitigation, treatment, or prevention of disease
```
But the description of `drug exposure` suggests the model is referring to all `chemical substance`s as `drugs`. That doesn't sound right. Doesn't this break the specialization outlined in the description of drug above which makes a distinction between drug and chemical substance relating to an intent to treat disease?

```
  drug exposure:
    aliases: ['drug intake', 'drug dose']
    is_a: environment
    description: >-
      A drug exposure is an intake of a particular chemical substance
#    slots:
#      - has input
    slot_usage:
      drug:
        range: chemical substance
        required: true
        multivalued: true
    mappings:
      - "ECTO:0000509"
      - SIO:001005
```

@mbrush @cmungall 

Possibly related to #119
