### ISSUE TITLE
need a biolink-model term for mouse strain

### ISSUE THREAD

**Issue by justaddcoffee** [biolink/biolink-model#236]
I'm looking for a biolink model term to represent mouse strain (C57black, BALB/c). This doesn't seem to exist now in biolink-model. I'm guessing this same term might be used to describe subspecies in other species besides mouse - human subpopulations, yeast strains, etc. Could we make a term for this, or could someone point me to the most appropriate term?

**Comment by justaddcoffee** [comment]
@deepakunni3

**Comment by cmungall** [comment]
There is an argument for including a subclass for strain/breed https://www.ebi.ac.uk/ols/ontologies/geno/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGENO_0000112

**Comment by TomConlin** [comment]
more fodder

#
# 			biospecimen			https://en.wikipedia.org/wiki/Biological_specimen
#		specimen			https://en.wikipedia.org/wiki/Zoological_specimen
# 		organism			https://en.wikipedia.org/wiki/Organism
# 	strain 				https://en.wikipedia.org/wiki/Strain_(biology)
#	breed				https://en.wikipedia.org/wiki/Breed
#	cultivar			https://en.wikipedia.org/wiki/Cultivar
#	hybrid				https://en.wikipedia.org/wiki/Hybrid_(biology)
#	landrace			https://en.wikipedia.org/wiki/Landrace

forma				https://en.wikipedia.org/wiki/Form_(botany)
varietas			https://en.wikipedia.org/wiki/Variety_(botany)
subspecies			https://en.wikipedia.org/wiki/Subspecies

**Comment by deepakunni3** [comment]
> There is an argument for including a subclass for strain/breed https://www.ebi.ac.uk/ols/ontologies/geno/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGENO_0000112

@cmungall Do we want to add a subclass for strain/breed?

**Comment by deepakunni3** [comment]
We could treat strain as an `organism taxon` for an `organism` class. 
What about breed, cultivar, landrace, etc.? These ought to be addressed by reusing `organism taxon`

**Comment by RichardBruskiewich** [comment]
In crop science (plants), there are global standards which tag different kinds of subpopulations, eg. landraces, etc. See http://aims.fao.org/vest-registry/metadata-sets/faoipgri-multi-crop-passport-descriptors

**Comment by TomConlin** [comment]
others
```
# 			biospecimen			https://en.wikipedia.org/wiki/Biological_specimen
#		specimen			https://en.wikipedia.org/wiki/Zoological_specimen
# 		organism			https://en.wikipedia.org/wiki/Organism
# 	strain 				https://en.wikipedia.org/wiki/Strain_(biology)
#	breed				https://en.wikipedia.org/wiki/Breed
#	cultivar			https://en.wikipedia.org/wiki/Cultivar
#	hybrid				https://en.wikipedia.org/wiki/Hybrid_(biology)
#	landrace			https://en.wikipedia.org/wiki/Landrace

forma				https://en.wikipedia.org/wiki/Form_(botany)
varietas			https://en.wikipedia.org/wiki/Variety_(botany)
```

**Comment by RichardBruskiewich** [comment]
Once again, in the world of (crop) plants, the various terms - landrace, hybrid, cultivar, etc. - have less to do with the biology of the plant than it has to do with their sociological, geographical or technical origin. There are, of course, typical genetic features of interest in each of these plants even if they are the same species. In many crop plants,  for example, rice, there are major ancient subtypes - Oryza sativa japonica, Oryza sativa indica, etc. - as well as many subpopulations specific to environments and regions. All of these categories could, in principle, be tagged as "Strains" although the term is not commonly used in (crop) plant science.

I suspect that if we simple introduce the Biolink model subclass "Strain" to designate a genetically distinct instance of a species (taxon), then we will adequately cover alot of ground.  Beyond that, all the rest is what we call "germplasm documentation".

**Comment by nlharris** [comment]
Should this still be assigned to @mbrush?

**Comment by sierra-moxon** [comment]
the model has:
```
  population of individual organisms:
    description: >-
      A collection of individuals from the same taxonomic class
      distinguished by one or more characteristics.  Characteristics can
      include, but are not limited to, shared geographic location, genetics,
      phenotypes [Alliance for Genome Resources]
    local_names:
      ga4gh: population
      agr: population
    mixins:
      - thing with taxon
    is_a: organismal entity
    exact_mappings:
      - PCO:0000001
      - SIO:001061
      # UMLS Semantic Type "Population Group"
      - STY:T098
      - OBI:0000181
    id_prefixes:
      - HANCESTRO
    in_subset:
      - model_organism_database
```
