### ISSUE TITLE
Make a separate biolink entity for locus

### ISSUE THREAD

**Issue by justaddcoffee** [biolink/biolink-model#242]
Currently locus is an alias for gene:

```
  gene:
    is_a: gene or gene product
    aliases: ['locus']
    class_uri: SO:0000704
    mappings:
```

That doesn't seem quite right to me. A gene (or other entity like a marker) is located at a locus, but is not exactly the same thing.
