### ISSUE TITLE
inconsistencies introduced by mappings should be surfaced when running validation on the model [was: Curies are mapped onto multiple categories]

### ISSUE THREAD

**Issue by lhannest** [biolink/biolink-model#25]
SIO:010004 maps to both molecular entity and chemical substance
SIO:010450 maps to both transcript and RNA product
SIO:010046 maps to anatomical entity, macromolecular complex, and gross anatomical structure
GENO:0000512 maps to both allele and sequence variant
WD:Q4936952 maps to both anatomical entity and gross anatomical structure

Mappings should be functions: each curie should map onto a single category. We could set up Travis CI to check these sorts of things on every pull request.

**Comment by lhannest** [comment]
@cmungall 
Some of these categories share an inheritance relationship: chemical substance is a molecular entity.
Some of these, like allele and sequence variant, are alliases:

```
  - name: allele
    is_a: genotype
    description: >-
      A genomic feature representing one of a set of coexisting sequence variants at a particular genomic locus
    alt_descriptions:
      - description: "An enitity that describes a single affected, endogenous allele.  These can be of any type that matches that definition"
        source: AGR
    slots:
      - has gene
    slot_usage:
      - slot: has gene
        multivalued: true
        description: Each allele can be associated with any number of genes
      - slot: id
        examples:
          - value: ZFIN:ZDB-ALT-980203-1091
            description: ti282a allele from ZFIN
    mappings:
      - "GENO:0000512"
      - SIO:010277

  - name: sequence variant
    aliases: ['allele']
    is_a: genomic entity
    description: >-
      A genomic feature representing one of a set of coexisting sequence variants at a particular genomic locus.
    mappings:
      - "GENO:0000512"
      - WD:Q15304597
```

Some like RNA product and transcript share a common ancestor class: both are ultimately a genomic entity.
