### ISSUE TITLE
Make it easy to view/download translator minimal set of relations

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#251]
We should have a page (md) and (tsv) for every subset in the model

E.g

```
  in taxon:
    is_a: related to
    domain: thing with taxon
    range: organism taxon
    description: >-
      connects a thing to a class representing a taxon
    in_subset:
      - translator_minimal
    slot_uri: RO:0002162
    mappings:
      - WD:P703
```

**Comment by andrewsu** [comment]
Going to add to this ticket because I think it's a highly related issue, but happy to create a new one if you prefer.  For the Translator Integration group, we needed the minimal set of relations, which pretty much corresponds to this page: https://biolink.github.io/biolink-model/docs/related_to.html.  But finding the relevant section/link out of the front page at https://biolink.github.io/biolink-model/docs/ was, well, very difficult.  Both Tyler and I missed it.  Not sure what the best organization of the front page would be, but I think a reorganization could be very helpful...

**Comment by andrewsu** [comment]
... and just to add a tiny bit more insight into the biolink noob perspective, I *thought* I'd found the right section under "associations" right at the top of https://biolink.github.io/biolink-model/docs/.  For example, I thought that under https://biolink.github.io/biolink-model/docs/ChemicalToGeneAssociation.html I'd see info on all the ways that chemicals and genes could be related.  So because I thought I'd found the right section already, I never scrolled further down to see the entry for "related to", which is in the "Slots" section.  (I suspect the heading "slots" will not be meaningful to most interested external users.)

**Comment by cmungall** [comment]
Note also we seem to have lost the mappings on the pages. e.g

https://biolink.github.io/biolink-model/docs/homologous_to

Expect to see SIO but it's not there

it is in the yaml

```
 homologous to:
    is_a: related to
    aliases: ['in homology relationship with']
    description: >-
      holds between two biological entities that have common evolutionary origin
    comments:
      - typically used to describe homology relationships between genes or gene products
    in_subset:
      - translator_minimal
    slot_uri: RO:HOM0000001
    mappings:
      - SIO:010302
```
