### ISSUE TITLE
drug is declared as a slot

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#265]
```
  drug exposure:
    aliases: ['drug intake', 'drug dose']
    is_a: environment
    description: >-
      A drug exposure is an intake of a particular chemical substance
#    slots:
#      - has input
    slot_usage:
      drug:
        range: chemical substance
        required: true
        multivalued: true
    class_uri: ECTO:0000509
    mappings:
      - SIO:001005
```

**Comment by vemonet** [comment]
Note that this slot is actually important to define the different drugs involved in a Drug Exposure

What is the issue here? Just the fact that `bl:drug` is misleading? (since we have already the class `bl:Drug` ). Then we would just need to rename it to something as 'has_drug' 

Or do we need to define it also as 'slots' like for the `bl:has_gene` slot?

This is an example of description of the slot `bl:has_gene`:
```yaml
slots:
      - has gene
    slot_usage:
      has gene:
        multivalued: true
        description: Each allele can be associated with any number of genes
      has biological sequence:
        description: >-
          The state of the sequence w.r.t a reference sequence
```
