### ISSUE TITLE
Mappings and id prefixes not showing up on pages

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#279]
E.g.https://biolink.github.io/biolink-model/docs/Protein

the yaml is much richer:

```
    class_uri: PR:000000001
    mappings:
      - SIO:010043
      - WD:Q8054
      # UMLS Semantic Type: "Amino Acid Sequence"
      - UMLSSC:T087
      - UMLSST:amas
      # Amino Acid, Peptide, or Protein
      - UMLSSC:T116
      - UMLSST:aapp
    id_prefixes:
      - UniProtKB
      - PR
      - ENSEMBL
```

also @mbrush @deepakunni3 @hsolbrig  we need to sort out the metamodel for mappings, and @RichardBruskiewich I don't think the UMLSSTs are correct?
