### ISSUE TITLE
sex qualifier not showing up on entity to phenotype

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#288]
I was expecting more association-specific slots to show up here: https://biolink.github.io/biolink-model/docs/GeneToPhenotypicFeatureAssociation.html

This has a mixin:

https://biolink.github.io/biolink-model/docs/EntityToPhenotypicFeatureAssociation.html

Which has yaml

```
  entity to phenotypic feature association:
    abstract: true
    defining_slots:
      - object
    is_a: association
    mixins:
      - entity to feature or disease qualifiers
    slot_usage:
      description:
        description: >-
          A description of specific aspects of this phenotype, not otherwise
          covered by the phenotype ontology class
      object:
        range: phenotypic feature
        description: "phenotypic class"
        values_from: ['upheno', 'hp', 'mp', 'wbphenotypic feature']
        examples:
          - value: HP:0002487
            description: Hyperkinesis
          - value: WBPhenotype:0000180
            description: axon morphology variant
          - value: MP:0001569
            description: abnormal circulating bilirubin level
    slots:
      - sex qualifier
```

however sex qualifier does not show up on either of the pages
