### ISSUE TITLE
Hypothetical modeling of specific pharmacological modes of action

### ISSUE THREAD

**Issue by andrewsu** [biolink/biolink-model#332]
Naive question here...  In the context of Translator, it seems likely that we will eventually want to model some detailed pharmacological modes of action, e.g., "antagonist" vs "inverse agonist".  As a strawman to better understand BioLink Model (and in advance of the formal discussion/approval of these decisions), can someone walk me through the way this _would_ be modeled?

I see an existing slot for `negatively regulates, entity to entity`:
```
  negatively regulates, entity to entity:
    aliases: ['activity directly negatively regulates activity of']
    is_a: regulates, entity to entity
    mixins:
      - negatively regulates
    local_names:
      translator: negatively regulates
      ro: activity directly negatively regulates activity of
    in_subset:
      - translator_minimal
    slot_uri: RO:0002449
    mappings:
      - SEMMEDDB:INHIBITS
```
So would antagonism and inverse agonism be modeled as another subclass slot? Would they be direct subclasses of `negatively regulates, entity to entity`, or would you create some intermediate class like `negatively regulates, chemical substance to gene or gene product`? Am I in the right ballpark here?
