### ISSUE TITLE
not all edge properties are shown on site

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#339]
E.g https://w3id.org/biolink/vocab/GenomicSequenceLocalization

isn't showing coordinate edge properties like start/end:

```
  genomic sequence localization:
    is_a: association
    description: >-
      A relationship between a sequence feature and an entity it is localized to. The reference entity may be
      a chromosome, chromosome region or information entity such as a contig
    slot_usage:
      subject:
        aliases: ['sequence feature']
        range: genomic entity  ## todo protein
      object:
        aliases: ['reference']
        range: genomic entity ## typically a chromosomel use monochrom
    slots:
      - start interbase coordinate
      - end interbase coordinate
      - genome build
      - phase
    class_uri: faldo:location
```
