### ISSUE TITLE
distribution.slot_uri is wrong

### ISSUE THREAD

**Issue by VladimirAlexiev** [biolink/biolink-model#366]
```yaml
  distribution:
    is_a: node property
    domain: data set version
    range: distribution level
    slot_uri: void:Dataset
```
But `void:Dataset` is a class while `distribution` is a slot.

You could use `dcat:distribution` which is used for the same purpose in ADMS.
