### ISSUE TITLE
Questions for G2P schema - relationship type, nested schemas

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolink-model#40]
In the [G2P schema](https://biolink.github.io/biolink-model/docs/GeneToPhenotypicFeatureAssociation.html) the range for relationship is RelationshipType.  However, [RelationshipType](https://biolink.github.io/biolink-model/docs/RelationshipType.html) does not contain any fields/slots, where I would expect at least id and label.  Or am I misinterpreting the spec?

Should certain fields contain nested schemas, e.g.

    publications = fields.Nested(PublicationSchema, many=True)

instead of

    publications = fields.Str()

Does provider need fields? https://biolink.github.io/biolink-model/docs/Provider.html

**Comment by cmungall** [comment]
the metamodeling gets a bit meta and punny here...

these should all be switched out from RelationshipType to slots

this has been done for some. Use this as an example

```
  - name: molecular interaction
    is_a: association
    mixin: true
    abstract: true
    description: >-
      An interaction at the molecular level between two physical entities
    slot_usage:
      - name: subject
        range: molecular entity
      - name: relation
        subproperty_of: "RO:0002436"
        range: molecularly interacts with
        values_from:
          - ro
          - mi
        description: "interaction relationship type"
        definitional: true
        examples:
          - value: RO:0002447
            description: the subject molecular phosphorylates the object molecule
```
