### ISSUE TITLE
non-standard prefix expansions injected into model

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#413]
```yaml
  CTD: 'http://translator.ncats.nih.gov/CTD_'
  hetio: 'http://translator.ncats.nih.gov/hetio_'
  SNPEFF: 'http://translator.ncats.nih.gov/SNPEFF_'
  Aeolus: 'http://translator.ncats.nih.gov/Aeolus_'
  DrugCentral: 'http://translator.ncats.nih.gov/DrugCentral_'
  ICD0: 'http://translator.ncats.nih.gov/ICD0_'
  ICD9: 'http://translator.ncats.nih.gov/ICD9_'
  ICD10: 'http://translator.ncats.nih.gov/ICD10_'
  MetaCyc: 'http://translator.ncats.nih.gov/MetaCyc_'
```

MetaCyc is in GO and idot, we shouldn't override

For ICD, we should sync with what mondo is doing
