### ISSUE TITLE
Add a predicate specifically for structural relationships between molecular structures

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#430]
**Scientific issue motivating this feature request:**
- Need to add chemical structural relationship mappings from relevant ontologies/controlled vocabularies to Biolink Model `edge_label `predicate space.

**Possible solution:**

Add a new Biolink Model predicate?

```
  structurally related to:
    is_a: related to
    description: holds between two molecular entities which have highly correlated primary chemical structures
    domain: molecular entity
    range: molecular entity
    exact_mappings:
      -
    broad_mappings:
      -
    narrow_mappings:
      # sample narrow mappings borrowed from S. Ramsey's recent curation of RTX... There may be others?
      - CHEBI:has_parent_hydride
      - CHEBI:is_conjugate_acid_of
      - CHEBI:is_conjugate_base_of
      - CHEBI:is_enantiomer_of
      - CHEBI:is_tautomer_of
```

**Origin of this request:**

The need for this change suggested by ongoing data modeling discussions about representing chemical similarities in the Biolink and some attempted mappings of chemical predicates (e.g. from CHEBI) to the model.

**Relevant members for discussion**
@cmungall, @cbizon, Steve Ramsay, Vlado Dancik
