### ISSUE TITLE
Travis build detected model error?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#437]
[Travis build model error](https://travis-ci.org/github/biolink/biolink-model/builds/725449022)  

I don't want to presume to fix it... the person who put this in originally should perhaps complete the semantics?

*ValueError: File "/home/travis/build/biolink/biolink-model/biolink-model.yaml", line 3877, col 25:  Slot: "genotype to genotype part association_relation" - subproperty_of: "has variant part" does not reference a slot definition*

for the following association:

```
genotype to genotype part association:
    is_a: association
    defining_slots:
      - subject
      - object
    description: >-
      Any association between one genotype and a genotypic entity that is a sub-component of it
    slot_usage:
      relation:
        subproperty_of: has variant part
      subject:
        range: genotype
        description: >-
          parent genotype
      object:
        range: genotype
        description: >-
          child genotype
```
