### ISSUE TITLE
When combining multiple prefix registries use case insensitivity

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#460]
https://biolink.github.io/biolink-model/context.jsonld

We have:

      "DBSNP": "http://identifiers.org/dbsnp/",
      "dbSNP": "http://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=",

We should use case insenstivity in the de-dupe step

note that as we prioritize idot, we'd end up with the ugly DBSNP, but we get the desired URL expansion

We discussed uppercasing of idot on call but agreed to keep for now

**Comment by RichardBruskiewich** [comment]
Rather than opening up a separate issue on the challenge of case sensitivity in general, I wish to point out the fact that in my curation of the RTX mappings into the biolink model, some mappings show up in both upper and lower case.  A specific example of this is that the original SEMMEDDB terms recorded in the model (pretty well as documented in the original Kilicoglu et al. article discussing them) are all in upper case (e.g. `SEMMEDDB:ASSOCIATED_WITH`) , whereas the same RTX reported terms are in lower case (e.g. `SEMMEDDB:associated_with`). I am recording both mappings for the moment, but perhaps we can decide how best to handle this situation, from a policy, BiolinkML and mapping usage perspective.

**Comment by deepakunni3** [comment]
@cmungall So this is a biolinkml ticket where the de-duplication step happens. Is there anything that ought to happen in the biolink model YAML?

One thing I noticed in the YAML is,
https://github.com/biolink/biolink-model/blob/b35922803e0cc490365a37cdf8a17521b002a75a/biolink-model.yaml#L3588-L3589

We have both `dbSNP` and `DBSNP` defined as valid id prefixes for SequenceVariant.

**Comment by hsolbrig** [comment]
# CURIE vs. URI
The current namespace identifier philosophy used in BiolinkML is based on the traditional model for identifiers:

* Every model element is uniquely identified by a URI.
* A URI can be represented in the form of `<prefix>:<value>`, where `prefix` represents the lhs portion of the URI and
`value` the rhs.
* Every `prefix` is associated with exactly one URI.
* Every URI can be associated with zero or more `prefix`es

## Assigning URIs to CURIE Prefixes
Biolink uses the following rules when it encounters a CURIE in a model:
1) If the CURIE prefix appears in the `prefixes` section of the model, the URI assigned to the CURIE is used
2) If not, the `default_curie_maps` are processed in the order they appear.  The URI associated with the first
map in which the CURIE prefix appears is assigned to the CURIE.
3) If the CURIE prefix does not appear in the `prefixes` section and is not found in the list of `default_curie_maps`,
a warning is issued and the prefix is assigned to the URI: `f"http://example.org/UNKNOWN/{prefix}/"`

Notes:
1) There is also code in `jsonldcontextgen.py#138` that assigns a URI to a prefix.  It is my guess that this code is
no longer used. (Will double check)

## Current Behavior
At the moment the following input:
```yaml
id: http://example.org/tests/curiecase
name: curiecase

prefixes:
  abc: http://example.org/abc#

classes:
  c1:
    class_uri: abc:c1


  c2:
    class_uri: ABC:t2

  c3:
    class_uri: aBc:t3
```
Issues the following warnings:
```text
WARNING:YAMLGenerator:Unrecognized prefix: ABC
WARNING:YAMLGenerator:Unrecognized prefix: aBc
WARNING:ContextGenerator:Unrecognized prefix: ABC
WARNING:ContextGenerator:Unrecognized prefix: aBc
```

It is represented internally as:
```yaml
name: curiecase
id: http://example.org/tests/curiecase
prefixes:
  abc:
    prefix_prefix: abc
    prefix_reference: http://example.org/abc#
default_prefix: http://example.org/tests/curiecase/
default_range: string
classes:
  c1:
    name: c1
    definition_uri: http://example.org/tests/curiecase/C1
    mappings:
    - abc:c1
    from_schema: http://example.org/tests/curiecase
    class_uri: abc:c1
  c2:
    name: c2
    definition_uri: http://example.org/tests/curiecase/C2
    mappings:
    - ABC:t2
    from_schema: http://example.org/tests/curiecase
    class_uri: ABC:t2
  c3:
    name: c3
    definition_uri: http://example.org/tests/curiecase/C3
    mappings:
    - aBc:t3
    from_schema: http://example.org/tests/curiecase
    class_uri: aBc:t3
metamodel_version: 1.6.0
source_file: curie_case.yaml
source_file_date: Thu Oct 29 13:29:22 2020
source_file_size: 196
generation_date: 2020-10-29 13:29
```
And emits the following JSON-LD Context:
```json
{
   "_comments": "Auto generated from curie_case.yaml by jsonldcontextgen.py version: 0.1.1\nGeneration date: 2020-10-29 13:29\nSchema: curiecase\n\nid: http://example.org/tests/curiecase\ndescription: \nlicense: \n",
   "@context": {
      "type": "@type",
      "ABC": "http://example.org/UNKNOWN/ABC/",
      "aBc": "http://example.org/UNKNOWN/aBc/",
      "abc": "http://example.org/abc#",
      "@vocab": "http://example.org/tests/curiecase/",
      "C1": {
         "@id": "abc:c1"
      },
      "C2": {
         "@id": "ABC:t2"
      },
      "C3": {
         "@id": "aBc:t3"
      }
   }
}
```

## Recommendations
### Case Sensitivity
I would propose that CURIE prefixes are "case aware" (there is an official term for this, but I don't remember it):
```yaml
prefixes:
  abc: http://example.org/abc#

types:
  t1:
    type_uri: abc:t1

  t2:
    type_uri: ABC:t2

  t3:
    type_uri: aBc:t3
```

Emits the following warnings:
```text
WARNING:YAMLGenerator:File "biolinkml/tests/test_issues/input/curie_case.yaml", line 10, col 16: Prefix case mismatch - supplied: abc expected: aBC
WARNING:YAMLGenerator:File "biolinkml/tests/test_issues/input/curie_case.yaml", line 14, col 16: Prefix case mismatch - supplied: ABC expected: aBC
WARNING:YAMLGenerator:File "biolinkml/tests/test_issues/input/curie_case.yaml", line 17, col 16: Prefix case mismatch - supplied: aBc expected: aBC
```
The output YAML preserves the original input:
```yaml
name: curiecase
id: http://example.org/tests/curiecase
prefixes:
  aBC:
    prefix_prefix: aBC
    prefix_reference: http://example.org/abc#
default_prefix: http://example.org/tests/curiecase/
default_range: string
classes:
  c1:
    name: c1
    definition_uri: http://example.org/tests/curiecase/C1
    mappings:
    - abc:c1
    from_schema: http://example.org/tests/curiecase
    class_uri: abc:c1
  c2:
    name: c2
    definition_uri: http://example.org/tests/curiecase/C2
    mappings:
    - ABC:t2
    from_schema: http://example.org/tests/curiecase
    class_uri: ABC:t2
  c3:
    name: c3
    definition_uri: http://example.org/tests/curiecase/C3
    mappings:
    - aBc:t3
    from_schema: http://example.org/tests/curiecase
    class_uri: aBc:t3
metamodel_version: 1.6.0
source_file: curie_case.yaml
source_file_date: Thu Oct 29 14:52:05 2020
source_file_size: 196
generation_date: 2020-10-29 14:52
```

And produces the following:
```json
{
   "_comments": "Auto generated from curie_case.yaml by jsonldcontextgen.py version: 0.1.1\nGeneration date: 2020-10-29 16:22\nSchema: curiecase\n\nid: http://example.org/tests/curiecase\ndescription: \nlicense: \n",
   "@context": {
      "type": "@type",
      "aBC": "http://example.org/abc#",
      "@vocab": "http://example.org/tests/curiecase/",
      "C1": {
         "@id": "aBC:c1"
      },
      "C2": {
         "@id": "aBC:t2"
      },
      "C3": {
         "@id": "aBC:t3"
      }
   }
}
```
The proposed changes for this can be found at:
https://github.com/biolink/biolinkml/tree/prefixcase -- see https://github.com/biolink/biolinkml/blob/prefixcase/tests/test_issues/test_curie_prefix_matching.py
