### ISSUE TITLE
Greater clarity on how to annotate classes with roles in the Biolink Model

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#488]
There are a number of circumstances where concepts could (or rather, should) be annotated with particular 'role' relationships within a knowledge graph. There are probably several ways to skin this cat but 'best practices' seems unclear.

## Example 1
The Biolink Model has one oddball class using the property tag `role:` as follows:

```
  gene regulatory relationship:
    is_a: association
    description: >-
      A regulatory relationship between two genes
    slot_usage:
      relation:
        description: >-
          the direction is always from regulator to regulated
      subject:
        range: gene or gene product
        role: regulatory gene
      object:
        range: gene or gene product
        role: regulated gene
```

where subject and object are given 'roles' as part of 'slot_usage'. However, this model tag is not defined anywhere. Not sure who put this in or if it is defined globally by BiolinkML. If the declaration and usage of this tag is clarified, could this help us annotate special roles into classes (via 'slot usage')

## Example 2

Publications may point to a list of authors. However, not all authors are created equal. Some, for example, may be designated as "Corresponding" (and possibly other attributes, like 'lead author' or 'senior author' or ???).

Such designations seem to be 'roles', but how does one annotated this nuance into a knowledge graph? This also depends on how we document instances of authors.  In principle, a list of author "curies" _could_ be listed as values for a multi-valued node property for Publications.  

Alternately, a "publication to author association" could be defined with can be used to document a relationship edge between a Publication instances and instances of a suitable actor class (nominally 'Provider' but perhaps a more precise class).  How best, though, to designate specific author nodes as 'corresponding'?   Simply making a special node which is a `subclass_of ` the ('provider') actor class then pointing to it seems like overkill The challenge here is that **Corresponding** is a special role that providers of information _sometimes_ (but not always) play in the publications to which they contribute.  Could/should a  'corresponding' term simply be inserted into the `qualifier` field of a knowledge assertion association between Publication and the ('provider') actor class in question?

Alternately, do we somehow document things as a `role` property or `has role` attribute somewhere?

## Example 3

Chemical substances (or perhaps, other kinds of biological entity) may have a distinct material identity but different roles of interpretation and usage within a given knowledge graph. A classic one is a gene product used as a drug, for example, insulin (which is a gene product of peptide nature) which is deployed as a treatment ('drug') for type 1 diabetes.  Is this also a case of somehow tagging the 'role' of such entities in some fashion, when they are used as nodes in graphs, or do we better capture the essence of this semantics using knowledge association/edges, e.g. insulin:GeneProduct-[has_role]->insulin:Drug ?  I think there has been some discussion in other issues elsewhere in the community to address this specific example, but general 'best practices' might enlighten us here.
