### ISSUE TITLE
Ensure mapped CURIEs are resolvable

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#508]
E.g.

```yaml
 has phenotype:
    is_a: related to
    description: >-
      holds between a biological entity and a phenotype, where a phenotype is construed broadly as any kind of quality of an organism part, a collection of these qualities, or a change in quality or qualities (e.g. abnormally increased temperature).
    domain: biological entity
    range: phenotypic feature
    notes:
      - check the range
    in_subset:
      - translator_minimal
    close_mappings:
      # RTX contributed term tagged as 'inverse'
      - OMIM:phenotype_of
    exact_mappings:
      - RO:0002200
      - RTXKG1:has_phenotype
      - SNOMED:characterized_by
    broad_mappings:
      # Disease–presents–Symptom; symptom or finding may be a phenotype but not necessarily
      - hetio:PRESENTS_DpS
      - NCIT:disease_may_have_finding
      - OMIM:has_phenotype
    narrow_mappings:
      - NCIT:disease_may_have_molecular_abnormality
      - OBO:doid#has_symptom
      - RO:0004022
```

Are these all resolvable via the json-ld context?

The NCIT OPs have PURLs like
http://purl.obolibrary.org/obo/NCIT_R115
is the doid hash correct?
