### ISSUE TITLE
Biolink Model 'affiliation' semantics requires elaboration

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#538]
The `biolink:Affiliation` currently (as of **master** branch commit https://github.com/biolink/biolink-model/commit/a96fb555666333a1f64a6bf9f6f43c5703d4249d) has the following definition:

```
  affiliation:
    is_a: node property
    description: >-
      a professional relationship between one provider (often a person) within another provider (often an organization).
      Target provider identity should be specified by a CURIE. Providers may have multiple affiliations.
    domain: agent
    range: uriorcurie
    multivalued: true
```

and is a slot in `biolink:Agent` as follows:

```
  agent:
    is_a: administrative entity
    aliases: ['group']
    description: >-
      person, group, organization or project that provides a piece of information (i.e. a knowledge association)
    slots:
      - affiliation
```

The semantics of _**affiliation**_ has plenty of room for elaboration.
