### ISSUE TITLE
Should 'mixin' classes be permitted in 'domain' and 'range' of a slot_usage... and what would this mean?

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#542]
Some instances of `mixin` serve as a kind of helpful semantic grouping of related node categories (predicates?) on distinct `is_a` inheritance hierarchies.  There are some situations where specifying such `mixin` entities as the `domain` or `range` of a given entity might be semantically meaningful and helpful.

However, biolinkml tags such values as erroneous simply because it expects concrete classes to be given as values. Could this constraint somehow be relaxed either across all mixins or perhaps, only for mixins somehow designated as special for this context?

**Comment by RichardBruskiewich** [comment]
I just noticed the following two definitions in the Biolink Model:

```yaml
  distribution level:
    is_a: data set version
    mixin: true
    abstract: true
    slots:
      - download url
    mappings:
      - dcat:Distribution

  distribution:
    aliases: ['dataset']
    is_a: node property
    domain: data set version
    range: distribution level
    exact_mappings:
      - void:Dataset
      - dctypes:Dataset
```

This implies that `mixin` classes can be used as `node property` values. Not sure if they are allowed elsewhere... I thought I saw an error generated, due to the abstract nature of the `mixin`, in other contexts, such as predicate slot `domain` and `range` properties.
