### ISSUE TITLE
Clarify policy regarding duplicate Biolink entity class, slot or mixin mappings. Fix duplication otherwise.

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#545]
Some Biolink Model entries may duplicate mappings relative to one another, e.g. 

```yaml
  source data file:
    is_a: node property
    domain: data set version
    range: data file
    broad_mappings:
      - dcterms:source

  source web page:
    is_a: node property
    domain: data set summary
    broad_mappings:
      - dcterms:source
```

have an identical `broad_mappings`. In fact, such a mapping may be true in some sense for this particular example.

However, the question is whether or not it is useful for Translator contexts like the [**Node Normalization**](https://github.com/TranslatorSRI/NodeNormalization) and  [**Edge Normalization**](https://github.com/TranslatorSRI/EdgeNormalization) tools.  Since the above example are two node property entries, neither tool will worry about this. However, if there is another context with an external developer needs to make a mapping onto the model, to either of these properties, from a knowledge source that has the `dcterms:source` attribute, then the mapping cannot be automatically done by lookup on the model.
