### ISSUE TITLE
new class: RNAi

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#558]
should link to the gene targeted, and any phenotypes

Example https://wormbase.org/species/c_elegans/rnai/WBRNAi00044514

**Comment by cmungall** [comment]
We have

```yaml
  reagent targeted gene:
    is_a: genomic entity
    description: >-
       A gene altered in its expression level in the context of some experiment as a result of being
       targeted by gene-knockdown reagent(s) such as a morpholino or RNAi
    exact_mappings:
      - GENO:0000504
```

But I'm not sure I see how this would be used. a gene is a gene regardless of how it is targeted. it seems we want a class for RNAi rather than RNAi targeted gene
