### ISSUE TITLE
Add examples on pages

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#560]
See #382 

https://biolink.github.io/biolink-model/docs/SequenceVariant

should show example values:

```yaml
      id:
        examples:
          - value: ZFIN:ZDB-ALT-980203-1091
            description: ti282a allele from ZFIN
          - value: ClinVarVariant:17681
            description: NM_007294.3(BRCA1):c.2521C>T (p.Arg841Trp)
```
