### ISSUE TITLE
Add opposite-ofs between predicates

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#657]
Depends on #656 

This ticket is for collecting all predicate pairs that are opposites, e.g. treats vs causes

**Comment by kvarforl** [comment]
Sourced from https://github.com/RTXteam/RTX/issues/979 back in september, in an effort for quality control of the RTX knowledge graph:

Here is my go at a list of antonym pairs. I tried to err on the side of too many pairs rather than too few, so that you all have the luxury of looking at them and saying "hmmm that doesn't seem quite right" rather than discovering pairs that I missed... hopefully :)

- negatively_regulates,_entity_to_entity, positively_regulates,_entity_to_entity				
- positively_regulates,_process_to_process, negatively_regulates,_process_to_process
- negatively_regulates, positively_regulates				
- has_not_completed, has_completed				
- decreases_activity_of, increases_activity_of				
- increases_expression_of, decreases_expression_of				
- contraindicated_for, treats
- contraindicated_for, prevents				
- predisposes, prevents				
- causes, prevents
- causes, treats				
- has_increased_amount, has_decreased_amount				
- increases_degradation_of, increases_stability_of
- increases_degradation_of, increases_expression_of				
- disrupts, enables				
- negatively_regulates, positively_regulates				
- has_input, has_output
- lacks_part, has_part
- lacks_part, part_of
- subclass_of, derives_into
- derives_from, derives_into

**Comment by sierra-moxon** [comment]
@mikebada - it looks like you are working on this one as part of the opposites project?

**Comment by mikebada** [comment]
My lab colleagues are working on oppositeness assertions among OBO classes and likely later on oppositeness assertions among assertions, so I can look into these oppositeness assertions among relations.

**Comment by mikebada** [comment]
I think these are referred to above but with different names:
entity_negatively_regulates_entity, entity_positively_regulates_entity
process_negatively_regulates_process, process_positively_regulates_process

I'd say that the following don't bear direct oppositeness:
contraindicated_for, prevents
contraindicated_for, treats
disrupts, enables
increases_degradation_of, increases_expression_of
increases_degradation_of, increases_stability_of
lacks_part, part_of
subclass_of, derives_into

I'd propose the following changes to predicates mentioned above:
decreases_degradation_of, increases_degradation_of
decreases_stability_of, increases_stability_of

I'd also suggest:
ameliorates, exacerbates
broad_match, narrow_match
enabled_by, prevented_by OR caused_by, prevented_by: differentiation between enabled_by & caused_by not clear to me
enables, prevents OR causes, prevents: differentiation between causes & enables not clear to me
decreases_abundance_of, increases_abundance_of
decreases_folding_of, increases_folding_of
decreases_localization_of, increases_localization_of
decreases_metabolic_processing_of, increases_metabolic_processing_of
decreases_molecular_interaction, increases_molecular_interaction
decreases_molecular_modification_of, increases_molecular_modification_of
decreases_mutation_rate_of, increases_mutation_rate_of
decreases_response_to, increases_response_to
decreases_secretion_of, increases_secretion_of
decreases_splicing_of, increases_splicing_of
decreases_synthesis_of, increases_synthesis_of
decreases_transport_of, increases_transport_of
decreases_uptake_of, increases_uptake_of
end_interbase_coordinate, start_interbase_coordinate
entity_negatively_regulated_by_entity, entity_positively_regulated_by_entity
has_active_ingredient, has_excipient
has_qualitative_value, has_quantitative_value
is_active_ingredient_of, is_excipient_of
latitude, longitude
molecular_activity_has_input, molecular_activity_has_output
negatively_correlated_with, positively_correlated_with
negatively_regulated_by, positively_regulated_by
preceded_by, precedes
process_negatively_regulated_by_process, entity_positively_regulated_by_process
subclass_of, superclass_of
transcribed_from, transcribed_to
translates_to, translation_of

In our lab's work on opposites, we're finding that (1) there are different kinds of oppositeness and (2) there may not always be one opposite for a given concept, as there may be multiple dimensions of oppositeness among the component concepts.

**Comment by sierra-moxon** [comment]
example of adding opposites to the model:
```slots:
  negatively regulates:
   annotations:
     extension_tag: biolink:opposite_of
     extension_value: positively regulates
   opposite_of: positively_regulates```

taken from @cmungall's comment in: [linkml repo](https://github.com/linkml/linkml/issues/131)

**Comment by mikebada** [comment]
Do we need to specify the opposite using both the annotation slot (with its subfields and values) and the opposite_of slot? This seems redundant to me...

**Comment by sierra-moxon** [comment]
I took a look at the linkml meta model and came up with this example/proposal (below) -- maybe we can take a quick look at the predicates meeting today? 

```    
negatively regulates:
    comments:
      - This is a grouping for negative process-process and entity-entity regulation.
    is_a: regulates
    inverse: negatively regulated by
    mixin: true
    close_mappings:
      # This RTX contributed term is tagged as a inverse of this Biolink predicate
      - RO:0002335
    exact_mappings:
      # Strict interpretation here is that entity A causally affects levels of B
      - RO:0004035
      - RO:0002212
    broad_mappings:
      # This term is slightly broader in that it includes that A acts within B as well
      - RO:0004033
    narrow_mappings:
      - CHEMBL.MECHANISM:blocker
      - CHEMBL.MECHANISM:inhibitor
      - CHEMBL.MECHANISM:negative_allosteric_modulator
      - CHEMBL.MECHANISM:negative_modulator
      - RO:0002630
    **annotation:
      extension_tag: biolink:opposite_of
      extension_value: positively regulates**

```
