### ISSUE TITLE
Value Set encoding and binding in Biolink

### ISSUE THREAD

**Issue by mbrush** [biolink/biolink-model#687]
How do we bind a property to a coding/value set in Biolink?  I see a couple different approaches being used - but neither is adequate to fully support value sets.

1. One approach defines the range as an ontology class, and defines a specific ontology in the 'values_from' field. An example of this is the ['interacting molecules category'](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L4584) property):

```
interacting molecules category:
   is_a: association slot
   range: ontology class
   exact_mappings:
      - MI:1046
   values_from:
      - MI
   examples:
      - value: MI:1048
   description: smallmolecule-protein
```
 
 
2. Another approach I see in use is to define a data type for the concept that the values describe, and constrain the values for this data type.  An example of this approach is the ['has evidence'](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L4538) property, and the ['evidence type'](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L5221 ) data type declared as its range.   The 'has evidence' definition defines 'evidence type' as its range . . . :

```
  has evidence:
      is_a: association slot
      range: evidence type
      description: >-
         connects an association to an instance of supporting evidence
       exact_mappings:
            - RO:0002558
 ```

. . . and the 'evidence type' data type decalres values of this data type to come from ECO:

```
evidence type:
   is_a: information content entity
   aliases: ['evidence code']
   description: >-
      Class of evidence that supports an association
   values_from:
      - eco
   exact_mappings:
      - ECO:0000000
 ```

----------------------
These seem to be two different ways to constrain values of a property to terms from a specific ontology.  Which is preferred/valid?  And when/how will the **LinkML extensions to support value set definitions and binding** that Harold and Dazhi are working on come into play. I think/hope that these will let us define specific sets of terms as value sets (not just point to an ontology from which values must come).  In our EPC modeling work, we will likely have need for this functionality, e.g. to define a value set of terms representing Translator KPs, or external knowledge sources - to use as values of properties that capture where a particular Association came from. 

Thoughts @cmungall @hsolbrig

**Comment by sierra-moxon** [comment]
- need to bring up on linkML call.

**Comment by nlharris** [comment]
@sierra-moxon reminder to bring up on linkML call.

**Comment by sierra-moxon** [comment]
@mbrush - you might be interested in 'semantic enumerations' from linkml?
ie:

```
relation_to_oxygen:
  is_a: nucleic acid sequence source field
  range: relation_to_oxygen_enum
  examples:
     - value: aerobe

relation_to_oxygen_enum:
  permissible_values:
     aerobe:
         description: dependent on oxygen
         meaning: PATO:0001455
     anaerobe:
        description: independent of oxygen
        meaning: PATO:0001456
```
