### ISSUE TITLE
Biolink Model use cases, tests, documentation

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#700]
- [x] #29

- [ ] Add examples on class pages such as https://biolink.github.io/biolink-model/docs/SequenceVariant #560. (See comment below for more info.)

- [x] #458

- [ ] Add example URIs to schema #228

Add tests such as:
- [ ] apply the KGX/BMT validation against Translator KP/ARAs graph metadata using the revised model, so highlight potential breaking changes.
- [ ] adding into the documentation examples of protein protein interaction
- [ ] https://github.com/biolink/biolink-model/issues/694

**Comment by nlharris** [comment]
At the suggestion of @sierra-moxon, merging in some items from other tickets (#29, #560, #458, #228) to reduce ticket clutter. 🙂

**Comment by nlharris** [comment]
Re: Add examples on class pages such as https://biolink.github.io/biolink-model/docs/SequenceVariant #560:

For example, https://biolink.github.io/biolink-model/docs/SequenceVariant should show example values:

```yaml
      id:
        examples:
          - value: ZFIN:ZDB-ALT-980203-1091
            description: ti282a allele from ZFIN
          - value: ClinVarVariant:17681
            description: NM_007294.3(BRCA1):c.2521C>T (p.Arg841Trp)
```
(see #382)

Related issue:#568, but  on the level of `biolink:Association` modelling  'use cases'
