### ISSUE TITLE
establish conventions for declaring 'canonical predicate'

### ISSUE THREAD

**Issue by sierra-moxon** [biolink/biolink-model#714]
Add an annotation to the model that declares that 'this' predicate is a canonical predicate.  

```
 treats:
    aliases: ['is substance that treats']
    is_a: ameliorates
    description: >-
      holds between a therapeutic procedure or chemical substance
      and a disease or phenotypic feature that it is used to treat
    domain: chemical or drug or treatment
    range: disease or phenotypic feature
    in_subset:
      - translator_minimal
    related_mappings:
      - MONDO:disease_responds_to
    annotations:
       - tag: biolink:canonical_predicate
          value: True

VS.

Just use the "in_subset" flag to highlight canonical inverses.

treats:
    aliases: ['is substance that treats']
    is_a: ameliorates
    description: >-
      holds between a therapeutic procedure or chemical substance
      and a disease or phenotypic feature that it is used to treat
    domain: chemical or drug or treatment
    range: disease or phenotypic feature
    in_subset:
      - translator_minimal
      - translator_canonical_inverses
    related_mappings:
      - MONDO:disease_responds_to
```

My vote is for the second option - just using the 'in_subset' mechanism.  @mikebada @cbizon @vdancik - do you have a preference?  

```
treated by:
 is_a: related to
 description: >-
   holds between a disease or phenotypic feature and a therapeutic
   process or chemical substance that is used to treat the condition
 domain: disease or phenotypic feature
 range: treatment
 in_subset:
   - translator_minimal
 inverse: treats
 exact_mappings:
   - WIKIDATA_PROPERTY:P2176
   # RTX contributed term tagged as inverse of 'biolink:treats'
   - MONDO:disease_responds_to
 narrow_mappings:
   # "is treated by substance" constrains statements to
   # subset of the universe of all possible treatments
   - RO:0002302
```
