### ISSUE TITLE
eliminate death

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#779]
```yaml
  death:
    is_a: biological process
    exact_mappings:
      - GO:0016265
```

why is this very specific process here? An ontology class should be used here, no need for this in the schema
