### ISSUE TITLE
canonical_predicate meta-predicate should have its own documentation page

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#829]
The 2.0 release docs https://biolink.github.io/biolink-model/Migration_2.0_Guide.html has

```
Inverses
added inverses for the majority of biolink predicates.
primary direction of predicate tagged with ‘biolink:canonical_predicate’.
```

this is v nice, and it's easy to see in the yaml:

```yaml
affects:
    is_a: related to
    description: >-
      describes an entity that has a direct affect on the state or quality
      of another existing entity. Use of the 'affects' predicate implies that
      the affected entity already exists, unlike predicates such as
      'affects risk for' and 'prevents, where the outcome is something
      that may or may not come to be.
    in_subset:
      - translator_minimal
    annotations:
      tag: biolink:canonical_predicate
      value: true
```

however, the URI for canonical_predicate doesn't resolve, It would be good if it had its own entry in the model yaml and thus its own URI/markdown page, showing the list of all elements that are tagged with this

we should also have some docs about how to obtain these programmatically but let's get bmt on rtd first

https://github.com/biolink/biolink-model-toolkit/issues/47
