### ISSUE TITLE
issues with STY mappings -- too many redundant narrow mappings, should be replaced with exact

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#832]
continued from #749. 

```
  organism taxon:
...
    exact_mappings:
      - WIKIDATA:Q16521
    narrow_mappings:
      # Virus
      - STY:T005
      - UMLSST:virs
      # Bacterium
      - STY:T007
      - UMLSST:bact
      # Archaeon
      - STY:T194
      - UMLSST:arch
      # Eukaryote
      - STY:T204
      - UMLSST:euka
      # Plant
      - STY:T002
      - UMLSST:plnt
      # Fungus
etc
```

This should be a straightforward mapping to STY:T001 (http://purl.bioontology.org/ontology/STY/T001)

![image](https://user-images.githubusercontent.com/50745/128106711-37bd6fcf-5998-4112-beed-eb3c37b0305d.png)

**Comment by cmungall** [comment]
Another one:

```
 gross anatomical structure:
    aliases: ['tissue', 'organ']
    is_a: anatomical entity
    exact_mappings:
      - UBERON:0010000
      - WIKIDATA:Q4936952
      # UMLS Semantic Type "Anatomical Structure"
      - STY:T017
      # UMLS Semantic Type "Fully Formed Anatomical Structure"
```

we should have an error if there is >1 exact mapping to the same system

![image](https://user-images.githubusercontent.com/50745/128107899-6073ade1-364e-4cb9-9ad7-8030ba380aa3.png)

so instead, biolink anatomical entity is exact mapping to STY anatomical structure, as it includes cells and cell parts

**Comment by cmungall** [comment]
another

```yaml
chemical entity:
    is_a: named thing
    mixins:
      - physical essence
      - chemical or drug or treatment # issue 701
      - chemical entity or gene or gene product
      - chemical entity or protein or polypeptide
    description: >-
      A chemical entity is a physical entity that pertains to chemistry or
      biochemistry.
    slots:
      - trade name
      - available from
    exact_mappings:
      - CHEBI:24431
      - SIO:010004 # Chemical entity
      - WIKIDATA:Q79529 # Chemical substance
    narrow_mappings:
      - WIKIDATA:Q43460564
      - STY:T103 # Chemical
      - STY:T120 # Chemical Viewed Functionally
      - STY:T104 # Chemical Viewed Structurally
      - STY:T197 # Inorganic Chemical
      - STY:T109 # Organic Chemical
      - STY:T125 # Hormone
      - STY:T123 # Biologically Active Substance
      - STY:T129 # Immunologic Factor
      - STY:T131 # Hazardous or Poisonous Substance
      # - STY:T130 # Indicator, Reagent, or Diagnostic Aid
    broad_mappings:
      - STY:T167 # Substance
    in_subset:
      - translator_minimal
    id_prefixes:
      - UNII
      - MESH
      - CAS #CAS numbers are given for things like plant extracts as well.
```

straightforward exact mapping 
![image](https://user-images.githubusercontent.com/50745/128108285-08482686-838c-41dc-a569-f21064f79320.png)
