### ISSUE TITLE
Annotate associations with Wikidata property URIs

### ISSUE THREAD

**Issue by stuppie** [biolink/biolink-model#9]
http://tinyurl.com/yactqzzm

**Comment by stuppie** [comment]
I don't really understand the associations are described

Under Slots (line 56) you have
```
  - name: in taxon
    domain: thing with taxon
    range: organism taxon
    description: >-
      connects a thing to a class representing a taxon
    mappings:
      - "RO:0002162"
```

line 1342:
```
  - name: gene to gene product relationship
    is_a: sequence feature relationship
    defining_slots:
      - subject
      - object
    description: >-
      A gene is transcribed and potentially translated to a gene product
    slot_usage:
      - name: subject
        range: gene
      - name: object
        range: gene product
      - name: relation
        subproperty_of: RO:0002205
```
Why is one mapped to RO and one is a subproperty? They look to be defined the same as in RO (a subject that is a gene -> transcribed to -> an object that is a gene product)

More importantly, how should I map to Wikidata (https://www.wikidata.org/wiki/Property:P688) ?
