### ISSUE TITLE
Modelling sets in Biolink

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#950]
**Is your feature request related to a problem? Please describe.**

The best practices for modelling sets of  things in Biolink remains somewhat undefined or, at best, heterogeneously defined.

**What working group (or team) did this request originate from?**

The Chemical Working Group (under leadership of Vlado Dancik) discussed the situation in their call of February 22nd, 2022.  Some extant Biolink Model issues reflect facets of this 'set modelling' issue may include the following (@vdancik, please add some more...):

- Issue #385 
- Issue #944 
- Issue #314 

**Describe the solution you'd like**

A unified Biolink Model and best practices approach may help here on several levels:

- Biolink Model strategy: do we model sets as special model syntax, mixins, or separate categories (see next bullet point)
- Biolink Model (node concept) categories: would a parent category `mathematical set` with 'major domain' specialist  child categories (e.g. `GeneFamily`, `ChemicalFamily`, `DiseaseFamily`, etc.) be helpful for knowledge representation and queries (or not)?
- BIolink Model predicates: Issue #944  suggests  the idea of `has member` and `member of` predicates  in  the `  related to at concept level:` predicate sub-hierarchy

**Tag relevant members for discussion**

@vdancik @sierra-moxon @cmungall @cbizon 

Examples possible model:

```yaml
mathematical set:
  mixin: true
```

```yaml
# a bit of a stretch of Biolink Model subclassing semantics here... 
# alongside the mixin, convention constrains instances of gene family to be sets only contain genes, 
# and that every member of the gene set satisfies the truth value of statements using the set as a subject or object?
gene set:
   is_a: gene   
   mixins:
   - mathematical set

gene family:
   is_a: gene set
   description: gene set defined by gene homology

chemical set:
    is_a: chemical entity
   mixins:
   - mathematical set
```

An alternate modelling approach might make mathematical set a first class node category, and simply constrain semantics of set members by associations, namely:

```yaml
mathematical set:
  is_a: named thing

gene to gene family association:
    is_a: association
    defining_slots:
      - subject
      - predicate
      - object
    slot_usage:
      subject:
        range: gene
      predicate:
         subproperty_of: member of
      object:
        range: mathematical set
```
