### ISSUE TITLE
Add id_prefixes under LifeStage

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#989]
under

```yaml
life stage:
    is_a: organismal entity
    mixins:
      - thing with taxon
    description: >-
      A stage of development or growth of an organism,
      including post-natal adult stages
    exact_mappings:
      - UBERON:0000105
    narrow_mappings:
      # constrained to human life cycles
      - HsapDv:0000000
    in_subset:
      - model_organism_database
```

add

```yaml
    id_prefixes:
      - HsapDv
      - MmusDv
      - WBls
      - ZFS
```

and any others r.g FBls
