### ISSUE TITLE
Add id_prefixes under AnatomicalEntity

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#990]
The current Anatomical Entity model 

```yaml
  anatomical entity:
    is_a: organismal entity
...
    description: >-
      A subcellular location, cell type or gross anatomical part
...
    id_prefixes:
      - UBERON
      - GO
      - CL
      - UMLS
      - MESH
      - NCIT
    ...
 ```

We want add the following:

- EMAPA
- ZFA
- FBbt
- WBbt

is missing some helpful model organism id prefixes.
